asb-admin:
  version: 0.0.1

website:
 url: http://localhost:8080
 footer: '2023 asb-admin'
 logo: /logo.png

spring:
  application:
    name: asb-admin
#  profiles:
#    active: dev
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
    mvc:
      path-matching:
        matching-strategy: ANT_PATH_MATCHER
  jackson:
    locale: zh_CN
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://localhost:3306/asb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT+8&allowPublicKeyRetrieval=true
    name: asb
    username: root
    password: root
  data:
    redis:
      host: 192.168.50.3
      port: 6379
      password:
      timeout: 30000
      database: 3
      jedis:
        pool:
          max-active: 200
          max-wait: -1
          max-idle: 10
          min-idle: 0
          time-between-eviction-runs: -1

debug: true
logging:
  level:
    com.wcz0.asb: info
    org.springframework.boot: warn
#  config: classpath:logback-spring.xml
#  file:
#      path: ./asb_log
id-generator:
  worker-id: 1
sa-token:
  token-name: Authorization
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true
  jwt-secret-key: t768pv1t5qkisahnpxsgyknkbxljns46
  token-prefix: Bearer


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
knife4j:
  enable: true
  setting:
    language: zh_cn