yunshuiban:
  version: YUNSHUIBAN-0.0.1
  domain: api.yunshuiban.com

spring:
  profiles:
    active:
  servlet:
    multipart:
      max-file-size: 50MB #设置单个文件大小
      max-request-size: 50MB #设置单次请求文件的总大小
  application:
    name: yunshuiban
  jackson:
    locale: zh_CN
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://test.yunshuiban.com:3306/yunshuiban?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT+8
    name: yunshuiban
    username: yunshuiban
    password: AGBGPEj32xDeYz5S

  data:
    redis:
      host: test.yunshuiban.com
      port: 6379
      password: jhkdjhkjdhsIUTYURTU_XH6sJE
      database: 2
      timeout: 30000
      jedis:
        pool:
          max-active: 200
          max-wait: -1
          max-idle: 10
          min-idle: 0
          time-between-eviction-runs: -1

debug: true
#logging:
#  level:
#    io.swagger.*: error
#    com.wcz0.yunshuiban: debug
#    org.springframework.boot.autoconfigure: ERROR
#  config: classpath:logback-spring.xml
#  file:
#    path: ./yunshuiban_log

druid:
    username: test
    password: 123456